title: DOTSLASHLINUX | Are You Ready? (Y/Y)
url: https://www.dotslashlinux.com
author: Firas Khalil Khana
description: GNU/Linux Enthusiasts' Hub
markdown: kramdown
gems:
  - jekyll-paginate
paginate: 6
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
