title: Are You Ready? (Y/Y) | ./LINUX
url: https://www.dotslashlinux.com
author: Firas Khalil Khana
description: GNU/Linux Enthusiasts' Hub
markdown: kramdown
gems:
  - jekyll-paginate
paginate: 16
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
